//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controller_Actions_Menu
    {
        public int ID { get; set; }
        public Nullable<int> ControllerID { get; set; }
        public Nullable<int> AksioniID { get; set; }
        public string Pershkrimi { get; set; }
    
        public virtual Controller_Actions_Menu Controller_Actions_Menu1 { get; set; }
        public virtual Controller_Actions_Menu Controller_Actions_Menu2 { get; set; }
        public virtual Controller_Menu Controller_Menu { get; set; }
    }
}
