//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GJEDHAT_PARAMETRAT
    {
        public int ID { get; set; }
        public Nullable<int> GjedhiID { get; set; }
        public Nullable<int> RrahjeteZemresID { get; set; }
        public Nullable<int> TemperaturaID { get; set; }
        public Nullable<int> LageshtiaID { get; set; }
        public Nullable<System.DateTime> DataMatjes { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        public virtual GJEDHI GJEDHI { get; set; }
        public virtual LAGESHTIA_AJRIT LAGESHTIA_AJRIT { get; set; }
        public virtual RRAHJET_ZEMRES RRAHJET_ZEMRES { get; set; }
        public virtual TEMPERATURA TEMPERATURA { get; set; }
    }
}
