//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GJEDHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GJEDHI()
        {
            this.GJEDHAT_PARAMETRAT = new HashSet<GJEDHAT_PARAMETRAT>();
            this.GJEDHI1 = new HashSet<GJEDHI>();
            this.QUMESHTIs = new HashSet<QUMESHTI>();
        }
    
        public int ID { get; set; }
        public string Emri { get; set; }
        public Nullable<int> FermaID { get; set; }
        public Nullable<int> RacaID { get; set; }
        public Nullable<int> PrindiID { get; set; }
        public Nullable<int> TipiID { get; set; }
        public Nullable<System.DateTime> Datelindja { get; set; }
        public Nullable<bool> Gjinia { get; set; }
        public string Vathe { get; set; }
        public Nullable<decimal> Pesha { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        public virtual FERMA FERMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJEDHAT_PARAMETRAT> GJEDHAT_PARAMETRAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJEDHI> GJEDHI1 { get; set; }
        public virtual GJEDHI GJEDHI2 { get; set; }
        public virtual RACA RACA { get; set; }
        public virtual TIPI TIPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUMESHTI> QUMESHTIs { get; set; }
    }
}
