//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int ID { get; set; }
        public string Controller { get; set; }
        public string Action_Metoda { get; set; }
        public string Emertimi { get; set; }
        public Nullable<int> Renditja { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    }
}
