//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.MENU_ROLI = new HashSet<MENU_ROLI>();
        }
    
        public int ID { get; set; }
        public string Controller { get; set; }
        public string Action_Metoda { get; set; }
        public string Emertimi { get; set; }
        public Nullable<int> Renditja { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_ROLI> MENU_ROLI { get; set; }
    }
}
