//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUMESHTI_DETAJET
    {
        public int ID { get; set; }
        public int FermaID { get; set; }
        public Nullable<System.DateTime> DataProdhimit { get; set; }
        public Nullable<decimal> TotalLitra { get; set; }
        public Nullable<decimal> UshqimViqave { get; set; }
        public Nullable<decimal> Humbjet { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        public virtual FERMA FERMA { get; set; }
        public virtual USER USER { get; set; }
    }
}
