//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUMESHTI
    {
        public int ID { get; set; }
        public int GjedhiID { get; set; }
        public Nullable<int> YndyraID { get; set; }
        public Nullable<int> KontaminimiID { get; set; }
        public decimal SasiaProdhuar { get; set; }
        public System.DateTime DataProdhimit { get; set; }
        public Nullable<System.DateTime> DataSkadimit { get; set; }
        public Nullable<System.DateTime> Krijuar { get; set; }
        public Nullable<int> KrijuarNga { get; set; }
    
        public virtual GJEDHI GJEDHI { get; set; }
        public virtual KONTAMINIMI KONTAMINIMI { get; set; }
        public virtual YNDYRA YNDYRA { get; set; }
        public int? UserID { get; internal set; }
    }
}
